import project from './db.js';

const data = project;
const body = document.getElementsByTagName('BODY')[0];
const main = document.querySelector('.main-section');
const cards = document.getElementById('portfolio');

for (let i = 0; i <= data.length - 1; i += 1) {
  const section = document.createElement('section');
  section.className = 'portfolio-list-section';
  section.setAttribute('id', `pop-up${i}`);
  const image = document.createElement('img');
  const image2 = document.createElement('img');
  image.className = 'mobile';
  image.setAttribute('src', `${data[i].image[0].imageSrc}`);
  image.setAttribute('alt', `${data[i].image[0].imageAlt}`);
  image.className = 'mobile';
  image2.setAttribute('src', `${data[i].image[1].imageSrc}`);
  image2.setAttribute('alt', `${data[i].image[1].imageAlt}`);
  image2.className = 'desktop';
  const div = document.createElement('div');
  div.className = 'project-description-container';
  const h2 = document.createElement('h2');
  h2.className = 'project-title';
  h2.textContent = `${data[i].name}`;
  const ul1 = document.createElement('ul');
  ul1.className = 'canopy-list';
  const li1 = document.createElement('li');
  li1.className = 'canopy';
  li1.textContent = `${data[i].featured[0].feature1}`;
  const li2 = document.createElement('li');
  li2.className = 'title-and-year';
  li2.textContent = `${data[i].featured[0].feature2}`;
  const li3 = document.createElement('li');
  li3.className = 'title-and-year';
  li3.textContent = `${data[i].featured[0].year}`;
  ul1.append(li1, li2, li3);
  const p = document.createElement('p');
  p.className = 'project-description';
  p.textContent = `${data[i].description}`;
  const ul2 = document.createElement('ul');
  ul2.className = 'teck-stacks';
  const li11 = document.createElement('li');
  li11.className = 'canopy';
  li11.textContent = `${data[i].technologies[0].teck1}`;
  const li22 = document.createElement('li');
  li22.className = 'title-and-year';
  li22.textContent = `${data[i].technologies[0].teck2}`;
  const li33 = document.createElement('li');
  li33.className = 'title-and-year';
  li33.textContent = `${data[i].technologies[0].teck3}`;
  ul2.append(li11, li22, li33);
  const button = document.createElement('button');
  button.className = 'btn';
  button.setAttribute('id', `btn${i}`);
  button.textContent = 'See Project';
  const popUpSection = document.createElement('div');
  popUpSection.className = 'pop-up-section';
  popUpSection.append(image, image2);

  div.append(h2, ul1, p, ul2, button);
  section.append(image, image2, div);
  cards.append(section);
  main.append(popUpSection);
}

const elements = document.querySelectorAll('.btn');
const popup = document.querySelectorAll('.pop-up-section');
const popUpBg = document.getElementById('popUp-bg');
const image = document.createElement('img');
const image2 = document.createElement('img');
const div = document.createElement('div');
const div1 = document.createElement('div');
const div2 = document.createElement('div');
const h2 = document.createElement('h2');
const ul1 = document.createElement('ul');
const li1 = document.createElement('li');
const li2 = document.createElement('li');
const li3 = document.createElement('li');
const p = document.createElement('p');
const ul2 = document.createElement('ul');
const li11 = document.createElement('li');
const li22 = document.createElement('li');
const li33 = document.createElement('li');
const seeLive = document.createElement('a');
seeLive.setAttribute('href', 'https://muhammedb8826.github.io/Portfolio/');
const seeSource = document.createElement('a');
seeSource.setAttribute('href', 'https://github.com/muhammedb8826/Portfolio');
const githubIcon = document.createElement('img');
const liveIcon = document.createElement('img');
const popUpTogglerBtn = document.createElement('a');
popUpTogglerBtn.innerHTML = '<img src="./assets/close-btn.png">';

for (let i = 0; i < data.length; i += 1) {
  elements[i].addEventListener('click', () => {
    body.classList.add('show');
    popUpTogglerBtn.className = 'toggle-to';
    popUpTogglerBtn.setAttribute('href', `#pop-up${i}`);
    popup[i].classList.add('show');
    popUpBg.classList.add('show');
    window.scrollTo(0, 0);
    image.className = 'mobile';
    image.setAttribute('src', `${data[i].image[0].imageSrc}`);
    image.setAttribute('alt', `${data[i].image[0].imageAlt}`);
    image.className = 'mobile';
    image2.setAttribute('src', `${data[i].image[1].imageSrc}`);
    image2.setAttribute('alt', `${data[i].image[1].imageAlt}`);
    image2.className = 'desktop';
    div1.className = 'techs-and-buttons';
    div.className = 'project-description-container-popup';
    h2.className = 'project-title';
    h2.textContent = `${data[i].name}`;
    ul1.className = 'canopy-list';
    li1.className = 'canopy';
    li1.textContent = `${data[i].featured[0].feature1}`;
    li2.className = 'title-and-year';
    li2.textContent = `${data[i].featured[0].feature2}`;
    li3.className = 'title-and-year';
    li3.textContent = `${data[i].featured[0].year}`;
    p.className = 'project-description';
    p.textContent = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent';
    ul2.className = 'teck-stacks';
    li11.className = 'canopy';
    li11.textContent = `${data[i].technologies[0].teck1}`;
    li22.className = 'title-and-year';
    li22.textContent = `${data[i].technologies[0].teck2}`;
    li33.className = 'title-and-year';
    li33.textContent = `${data[i].technologies[0].teck3}`;
    div2.className = 'live-and-source-btn';
    seeLive.className = 'btns';
    seeSource.className = 'btns';
    seeLive.textContent = 'See Live';
    seeSource.textContent = 'See Source';
    liveIcon.setAttribute('src', './assets/live-icon.png');
    liveIcon.className = 'live-icon';
    seeLive.append(liveIcon);
    githubIcon.setAttribute('src', './assets/github-icon.png');
    githubIcon.className = 'github-icon';
    seeSource.append(githubIcon);
    ul2.append(li11, li22, li33);
    ul1.append(li1, li2, li3);
    div2.append(seeLive, seeSource);
    div1.append(ul2, div2);
    div.append(p, div1);
    popup[i].append(h2, ul1, image, image2, div, popUpTogglerBtn);
    body.appendChild(popup[i]);
  });
}

popUpTogglerBtn.addEventListener('click', () => {
  for (let i = 0; i < data.length; i += 1) {
    body.classList.remove('show');
    popup[i].classList.remove('show');
    popUpBg.classList.remove('show');
  }
});
